# Generated by Django 3.0 on 2020-07-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AddField(
            model_name='post',
            name='idpost',
            field=models.AutoField(default=5656, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
